name: NuGet package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore
      working-directory: ./src
      run: dotnet restore
      
    - name: Build
      working-directory: ./src
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      working-directory: ./src
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish package
      if: github.ref == 'refs/heads/main'
      working-directory: ./src
      run: dotnet nuget push ./**/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source "https://nuget.pkg.github.com/dyroydev/index.json" --skip-duplicate
